spring:
  application:
    name: SpringDataRedisDemo

  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 20  # MaxConnection Number
          max-idle: 8 # MaxAvailableConnection Number
          min-idle: 0 # MinAvailableConnection
          max-wait: 100 # Time(ms) wait for Connection


